### ISSUE TITLE
run datahub ingest failed

### ISSUE THREAD

**Issue by liqi444** [linkedin/datahub#2309]
hi everyone 
i got failed when i run "datahub ingest -c ./examples/recipes/mysql.yml".help me please,thanks
debug log :
  {datahub.entrypoints:64} - Using config: {'source': {'type': 'mysql', 'config': {'username': 'root', 'password': 'root', 'database': 'mydatebase', 'host_port': 'localhost:3307', 'table_pattern': {'deny': ['performance_schema'], 'allow': ['mydatebase.my_table']}}}}

message:
1 validation error for PipelineConfig
sink
  field required (type=value_error.missing)

**Comment by hsheth2** [comment]
Hi @liqi444 - you'll need to add a sink to your recipe configuration as well - see these docs: https://datahubproject.io/docs/metadata-ingestion/#sinks. 

For example, if you started DataHub using the quickstart guide, you might do this:
```yml
source: <same as before>

sink:
  type: "datahub-rest"
  config:
    server: 'http://localhost:8080'
```
