### ISSUE TITLE
Add transformation step to ingestion pipeline

### ISSUE THREAD

**Issue by thomasplarsson** [linkedin/datahub#2410]
**Is your feature request related to a problem? Please describe.**
Currently the ingestion pipeline consists of sources that produce MetadataChangeEvents and sinks which consume them. With these blocks it’s possible to extend the ingestion framework by writing custom variants of them. Typically this is done when there is a source from which data is needed but for which there isn’t an existing plugin.

In some cases though there is a source plugin but there is still a need to customise its behaviour. Examples of this could be that dataset names should be modified, extra tags should be added, ownership metadata should be attached etc.

This can be achieved by customising an existing source but that has several downsides such as low reusability and increased complexity of the resulting source.

**Describe the solution you'd like**
An alternative to that would be if a pipeline included an intermediate step between source and sink, where the records could be transformed. That would remove the need to customise existing code in favour of writing smaller transformer classes.

The example interface would look something like 

```
class Transformer:
   @abstractmethod
   def transform(self, records: Iterable[RecordEnvelope]) -> Iterable[RecordEnvelope]:
       """
       Transforms a sequence of records.
       :param records: the records to be transformed
       :return: 0 or more transformed records
       """

```

An example pipeline configuration would look like

```
source:
 type: "file"
 config:
   filename: "./examples/mce_files/bootstrap_mce.json"

transforms:
 - type: "mycompany.transforms.PrefixNames"
   config:
     prefix: "some.prefix"
 - type: "mycompany.transforms.AddTags"
   config:
     tags:
       - name: "tagA"
         value: "valueA"

sink:
 type: "file"
 config:
   filename: './example_output_mces.json'
```

**Describe alternatives you've considered**
Writing customised versions of sources.

**Additional context**
