### ISSUE TITLE
Adding tag, ownership, properties values from yaml files

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2492]
If I understand the [documentation](https://datahubproject.io/docs/metadata-ingestion/#transformations) correctly, it says I can add ownership information, tags and properties for inserted data by including a transformers field in the ingested yml files.

For example, I want to try to ingest `bootstrap_mce.json` with an additional tag "testtag". I define my yml file like this:
```
---
source:
  type: "file"
  config:
    filename: "bootstrap_mce.json"

sink:
  type: "datahub-rest"
  config:
    server: 'http://localhost:8080'

transformers:
  - type: "fully-qualified-class-name-of-transformer"
    config:
      tags: "testtag"
```

Under type I need to define a transformer. The documentation says that "at the moment there are no built-in transformers." Does this mean this feature is currently not available yet?
If it is, how do I change the above yml file to add the tag information?

**Comment by hsheth2** [comment]
Hi @iremi - the feature is available right now, but you'd need to write some custom code in order to make it work. Under transformer type, you'd specify the path to the `Transformer` class that you'd like to use.

I'm currently working on building a couple pre-built transformers that will enable setting owners/tags without writing custom code.

**Comment by iremi** [comment]
That's great, thank you for the answer.
If you don't mind me asking: when can I expect these pre-built transformers to be available?

**Comment by hsheth2** [comment]
@iremi - I'm hoping to build them today or tomorrow

**Comment by iremi** [comment]
Great. Please let me know when they're added.

**Comment by hsheth2** [comment]
@iremi #2532 is the first step - a transformer for adding ownership information. I'll probably also build a tag transformer soon. Additionally, the implementation should also serve as a good reference for any custom transformers you need to write for more bespoke sorts of transformations.

**Comment by iremi** [comment]
Hey @hsheth2. Thanks for the update and also the documentation on the metadata ingestion page. 
When I'm trying to use the transformer I get the following error:
`KeyError: 'Did not find a registered class for simple_add_dataset_ownership'`

I've updated to the latest datahub version. The yaml file I'm ingesting is the following:
```
---
source:
  type: mssql
  config:
    username: user
    password: pass
    host_port: port
    database: db
  
sink:
  type: "datahub-rest"
  config:
    server: 'http://localhost:8080'
    
transformers:
  - type: "simple_add_dataset_ownership"
    config:
      owner_urns:
        - "urn:li:corpuser:test"
```
I get the same result with `AddDatasetOwnership`
