### ISSUE TITLE
Support for accessing Kafka schema registry in Confluent Cloud

### ISSUE THREAD

**Issue by dougallaninthecloud** [linkedin/datahub#2504]
**Is your feature request related to a problem? Please describe.**
Have been spinning up Kafka Cluster and schema registry in Confluent Cloud it seems the broker connection is fine and the topic data is pulled in, but the scheme registry is not authorised... I have looked through the code and it seems there is no support for passing API Key and secret specific for schema registry  

**Describe the solution you'd like**
Would be great if additional options/parameters could be passed in via the the ingestion recipe to tell it to use key:secret as per the confluent docs... I think it would be great to see this working against Confluent Cloud

**Describe alternatives you've considered**
will investigate doing this on local Kafka Cluster in the meantime

**Additional context**

**Comment by hsheth2** [comment]
Hi @dougallaninthecloud, have you tried using the schema registry client's user info option? Here's what the recipe might look like:

```yml
source:
  type: "kafka"
  config:
    connection:
      # bootstrap and connection config as before
      schema_registry_url: "https://<SR ENDPOINT>"
      schema_registry_config:
        basic.auth.user.info: "<SR API KEY>:<SR API SECRET>"
```
