### ISSUE TITLE
LookML files not found in nested directory structure

### ISSUE THREAD

**Issue by jameslamb** [linkedin/datahub#2879]
**Describe the bug**

In previous releases (at least as of 0.8.5.1), `datahub ingest` used to ingest Looker metadata in LookML model files would find all `.model.lkml` files located at least one directory beneath the one given in the `base_folder` field in the ingestion recipe.

Starting in 0.8.5.2, it seems that now `datahub ingest` will only recognize `.model.lkml` files that are directly below `base_folder`.

**To Reproduce**

Using `acryl-datahub[lookml, datahub-kafka]==0.8.6.0`, I'm ingesting Looker metadata extracted from LookML model files, following https://datahubproject.io/docs/metadata-ingestion/#lookml-lookml.

```shell
datahub ingest -c recipes/recipe.yaml
```

With `recipe.yaml` that looks like this.

```yaml
source:
  type: lookml
  config:
    base_folder: /lookml-model-files
    connection_to_platform_map:
      presto: presto
    platform_name: looker
    env: "PROD"
    parse_table_names_from_sql: False

sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: "${KAFKA_BOOTSTRAP_SERVER}"
      producer_config:
        security.protocol: SSL
        ssl.ca.location: /etc/service/keys/ca
        ssl.certificate.location: /etc/service/keys/cert
        ssl.key.location: /etc/service/keys/key
      schema_registry_url: "${KAFKA_SCHEMA_REGISTRY_URL}"
      schema_registry_config:
        basic.auth.user.info: "${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PW}"
```

On `acryl-datahub==0.8.5.1`, all of the model files are found. Starting with `acryl-datahub==0.8.5.2`, none are found and the following logs are produced.

> [2021-07-14 16:00:14,335] INFO     {datahub.entrypoints:84} - Starting metadata ingestion
[2021-07-14 16:00:14,336] INFO     {datahub.entrypoints:86} - Finished metadata ingestion

> Source (lookml) report:
{'failures': {},
 'filtered_models': [],
 'filtered_views': [],
 'models_scanned': 0,
 'views_scanned': 0,
 'warnings': {},
 'workunit_ids': [],
 'workunits_produced': 0}

The directory `/model-files` looks something like this

```text
/model-files
|
|__ Accounting
    |__ general.model.lkml
|_ Finance
    |__ something.model.lkml
```

For such a structure, the `glob` pattern introduced in #2851 will not find those nested `.model.lkml` files. The `glob` pattern used in earlier versions of `datahub` does find them.

```shell
mkdir -p /model-files /model-files/Accounting /model-files/Finance
touch /model-files/Accounting/general.model.lkml
touch /model-files/Finance/general.model.lkml

# does not match any files
python -c "import glob; print(glob.glob('/model-files/**.model.lkml', recursive=True))"
# []

# matches both files
python -c "import glob; print(glob.glob('/model-files/**/*.model.lkml', recursive=True))"
# ['/model-files/Accounting/general.model.lkml', '/model-files/Finance/general.model.lkml']
```

**Expected behavior**

I expected that all `.model.lkml` files found *at arbitrary depth* beneath `base_folder` would be considered by `datahub-ingest`.

If that is the expected behavior for `datahub-ingest`, then I think #2851 should be considered a regression, and the glob pattern at

https://github.com/linkedin/datahub/blob/a6dc9e0dc0946bcc8f6bdcb6878520581fe05616/metadata-ingestion/src/datahub/ingestion/source/lookml.py#L514

should be updated to achieve that behavior.

**Screenshots**

None

**Desktop (please complete the following information):**

I'm running `datahub ingest` in a container using the `python:3.7-slim` image.

**Additional context**

If maintainers agree with me that #2851 was a regression and that it's desirable for `datahub ingest` to recognize all `.model.lkml` files found at arbitrary depth below `base_folder`, I'd be happy to submit a pull request to fix this!

If not, I'd like to request that the documentation for LookML ingestion recipes (which I think is limited to the code comments at https://datahubproject.io/docs/metadata-ingestion/#lookml-lookml), be updated to make the expectation clear that all files have to be at the root of the folder provided by `base_folder`.

Thanks for your time and consideration.
