### ISSUE TITLE
DBMS avatars not being displayed

### ISSUE THREAD

**Issue by Light310** [linkedin/datahub#3060]
**Describe the bug**
I'm working with 2 versions of Datahub, the latest one and the one that I pulled few months ago. The latest version is not displying any DBMS Avatars. I've checked it for Kafka topics, the kafka icon is not displayed, also in the console I can see an error:
"raw.githubusercontent.com/linkedin/datahub/master/datahub-web/packages/data-portal/public/assets/images/default_avatar.png:1 Failed to load resource: the server responded with a status of 404"
So 1st of all it fails to get the icon, and 2nd - it tries to use a default icon for some reason (older version displays kafka icon on the same "dataset" correctly).

Also, if possible, please add icons for ClickHouse and Exasol.

**To Reproduce**
Ingest any dataset with platform "Kafka" and search for it in the UI.

**Expected behavior**
Kafka icon is displayed near the dataset name

**Desktop (please complete the following information):**
Ubuntu 20.02

**Comment by remisalmon** [comment]
@Light310 this sounds like the same issue I opened after 0.8 was released: https://github.com/linkedin/datahub/issues/2795

**Comment by jjoyce0510** [comment]
Hi there! You may need to ingest data_platforms.json is this instance. In old versions we loaded data platforms from the java resources but have since switched to ingesting them via the normal ingest path. 

You can ingest them either using the `bootstrap_mce.json` file or by ingesting the `data_platforms.json` file:

```
---
# see https://datahubproject.io/docs/metadata-ingestion/source_docs/file for complete documentation
source:
  type: "file"
  config:
    filename: ./examples/mce_files/data_platforms.json

# see https://datahubproject.io/docs/metadata-ingestion/sink_docs/datahub for complete documentation
sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: localhost:9092
```
