### ISSUE TITLE
Getting "UnboundVariable: ': unbound variable'" while performing ingestion

### ISSUE THREAD

**Issue by prabhur** [linkedin/datahub#3225]
Ingestion type: Snowflake 
The ingestion yaml file is has the keys mentioned in the guide.

```
source:
  type: snowflake
  config:
    # Coordinates
    host_port: ****
    warehouse: "*****"

    # Credentials
    username: ****
    password: ****
    role: "****"

    # Options
    top_n_queries: 10

sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```
However I keep getting this error. Seems like I may be missing something. I also verified that the yaml is fine syntax wise. In the error log, I do see a bunch of env variables being assigned to values properly. I'm running this on a macOS Catalina via Docker.

```
UnboundVariable: ': unbound variable'
```

Thanks!
