### ISSUE TITLE
Kafka metadata source not using source.config.connection.schema_registry_config

### ISSUE THREAD

**Issue by lvicentesanchez** [linkedin/datahub#3701]
**Describe the bug**
The Kafka source can't authenticate against the Schema Registry; config like the following don't work:

```
source:
  type: "kafka"
  config:
    connection:
      bootstrap: "localhost:9092"
      consumer_config:
        security.protocol: "SASL_SSL"
        sasl.mechanism: "PLAIN"
        sasl.username: "kafka_key"
        sasl.password: "kafka_secret"
      schema_registry_url: "https://localhost:8081"
      schema_registry_config:
        basic.auth.user.info: "schema_key:schema_secret"
```

**To Reproduce**
1. Setup a Kafka source with a config similar to the one above.
2. Use the datahub cli to ingest metadata using that source.
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I will create a PR that fixed this in our fork of the Kafka source.
