### ISSUE TITLE
OpenApi Metadata plugin not able to produce workunit 

### ISSUE THREAD

**Issue by neojunjie** [linkedin/datahub#3906]
**Describe the bug**
While importing OpenApi metadata for our lookup API , I ran into some occurrences where the recipe was not able to produce any workunit for the ingestion.

**To Reproduce**
No workunit produced by setting {name} as string value. The report generated warning even when forced_examples variable is set. The warning message was "Field in swagger file does not give consistence data, Unable to find an example for endpoint. Please add it to the list of forced examples"

```
source:
  type: openapi
  config:
    name: test_endpoint 
    url: https://test_endpoint.com/
    swagger_file: classicapi/doc/swagger.json  
    get_token: True 
    forced_examples: 
      /accounts/groupname/{name}: test
```

However, I got it to work by setting {name} as array of string and 1 workunit was produced.
```
source:
  type: openapi
  config:
    name: test_endpoint 
    url: https://test_endpoint.com/
    swagger_file: classicapi/doc/swagger.json  
    get_token: True 
    forced_examples: 
      /accounts/groupname/{name}: ['test']
```

**Expected behavior**
Should support both string value and array of strings.

**Additional context**
