### ISSUE TITLE
ValueError: This version of acryl-datahub requires GMS v0.8.0 or higher 

### ISSUE THREAD

**Issue by duylamvo-wefox** [linkedin/datahub#3918]
Error while trying with datahub-rest. It throw an error of GMS version is outdated. 

**Describe the bug**

**To Reproduce**
1. install acryl-datahub
2. run 
```
datahub docker quickstart

```
3. create recipe:
```yaml
source:
    type: 'postgres'
    config:
        host_port:  'localhost:7432' # port can be different my local is 7432 not 5432
        database:   'sportsdb'
        username:   'postgres'
        password:   'postgres'
sink:
    type: 'datahub-rest'
    config:
         server: 'http://localhost:9002'

```
4. it thrown errors
```bash
ValueError: This version of acryl-datahub requires GMS v0.8.0 or higher
❯ datahub --version
acryl-datahub, version 0.8.22.1
```
But when using datahub-kafka, it works normally.

**Expected behavior**
It should import data to datahub

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Os 10.15
 - Browser Chrome
 - Version 97.0.4692.7

**Additional context**
Change to datahub-kafka type works for me.
