### ISSUE TITLE
Azure AD groups not displaying members

### ISSUE THREAD

**Issue by razvan-am** [linkedin/datahub#3981]
**Describe the bug**
Groups imported from Azure AD don't show it's members + users don't inherit the group roles.

**To Reproduce**
1. Import Azure groups (+ members)
2. Go to users and Groups
3. Select one Group that has members (0+ members - numbers are displayed)
4. For a split second the members are displayed but then disappear

**Expected behavior**
Group members should be displayed.

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/94355655/151190627-22177fe1-02d8-4e0c-a054-3347d3bd142a.png)

2. 
![image](https://user-images.githubusercontent.com/94355655/151192826-11db6da1-2017-4e90-b308-8d2031d3a135.png)
3. inspect
![image](https://user-images.githubusercontent.com/94355655/151194966-12200ea9-b73d-43bc-ab5a-2013f1e37b5e.png)

After inserting the groups (and users) from Azure AD we have the following situation:

Good:
- Users are imported;
- Groups are imported;
- User count in groups are shown;
- groups of the user are shown.

BAD:
- users of each group are not listed/shown;
- users don't inherit the privileges of the groups;

Other details:
- for a split second the users (members) of the group i'm opening are shown but then are overwritten visually;
- when inspecting the page, one graphql lists the group+ users but after it there are multiple search results that apparently overwrite the initial result.

**Comment by jjoyce0510** [comment]
Thank you for reporting this! Taking a look.

**Comment by jjoyce0510** [comment]
I'm assuming you've imported groups using this connector? https://datahubproject.io/docs/metadata-ingestion/source_docs/azure-ad/

**Comment by jjoyce0510** [comment]
Also - which version of client / server are you using?

**Comment by razvan-am** [comment]
@jjoyce0510 yes, that is the connector. 
```
DataHub CLI version: 0.8.23.1
Python version: 3.9.1 (default, Jan 15 2022, 19:46:20)
[Clang 13.0.0 (clang-1300.0.29.30)]
```

from the deployed helm chart:
`datahub-gms:
  enabled: true
  image:
    repository: linkedin/datahub-gms
    tag: "v0.8.23"

datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    tag: "v0.8.23"
  # Set up ingress to expose react front-end
  ingress:
    enabled: false`

**Comment by razvan-am** [comment]
Even though i've sent you the ingestion recipe i'll also paste it here for reference:

```
ource:
  type: "azure-ad"
  config:
    client_id: "<client_id>"
    tenant_id: "<tenant_id>"
    client_secret: "<secret>"
    redirect: "https://login.microsoftonline.com/common/oauth2/nativeclient"
    authority: "https://login.microsoftonline.com/<auth>"
    token_url: "https://login.microsoftonline.com/<tenant>/oauth2/token"
    graph_url: "https://graph.microsoft.com/v1.0"
    ingest_users: False
    ingest_groups: True
    ingest_group_membership: True
    ingest_groups_users: True
    azure_ad_response_to_username_attr: "userPrincipalName"
    azure_ad_response_to_username_regex: "(.*)"
    groups_pattern:
      allow:
        - "AMI - VPN - data_and_bi"
    users_pattern:
      allow:
        - ".*"

sink:
  type: "datahub-rest"
  config:
    server: "http://my_server:8080"
```
